# This is script for https://cloud.google.com/cloud-build/
steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Lint
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'lint']
# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'unittest']
# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  env:
  - 'REACT_APP_BACKEND_URL=http://testiotdev:8080/api/v1'
  - 'NODE_PATH=./src'
# Deploy
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-d", "-r", "build", "gs://jaisona123"]
# Grant public permission
# TODO: it should be remove, by setting default permissions for the bucket.
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "acl", "ch", "-u", "AllUsers:R", "gs://jaison123/**"]	  
